language: android
sudo: required
dist: precise
jdk: oraclejdk8
os:
    - linux
env:
  global:
    - ANDROID_API_LEVEL=26
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi armeabi-v7a --skin 480x800
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew clean build lint test connectedCheck
